### ISSUE TITLE
Contributor on boarding instructions do not lead to working development environment

### ISSUE THREAD

**Issue by AlexisBRENON** [prebid/Prebid.js#11296]
## Type of issue

Bug

## Description

I am unable to setup a working local development environment, either directly, using VSCode Dev Container or Docker.

## Steps to reproduce

In your shell:

```bash
docker run --rm -it --entrypoint bash mcr.microsoft.com/vscode/devcontainers/javascript-node:12
```

Then in the container shell:
```bash
git clone https://github.com/greenbids/Prebid.js.git
cd Prebid.js/
nvm install
nvm use
npm install gulp-cli -g
npm ci
gulp lint
```

### Expected results

I expect the `gulp lint` command to execute properly, either raising concerns about non-linted files or being silent if anything is right.

### Actual results

```bash
root ➜ / $ git clone https://github.com/greenbids/Prebid.js.git
Cloning into 'Prebid.js'...
remote: Enumerating objects: 63827, done.
remote: Counting objects: 100% (961/961), done.
remote: Compressing objects: 100% (615/615), done.
remote: Total 63827 (delta 596), reused 600 (delta 342), pack-reused 62866
Receiving objects: 100% (63827/63827), 61.57 MiB | 20.55 MiB/s, done.
Resolving deltas: 100% (47683/47683), done.
root ➜ / $ cd Prebid.js/
root ➜ /Prebid.js (master) $ nvm install
Found '/Prebid.js/.nvmrc' with version <12.16.1>
Downloading and installing node v12.16.1...
Downloading https://nodejs.org/dist/v12.16.1/node-v12.16.1-linux-x64.tar.xz...
######################################################################################################################################################################################################################################################### 100.0%
Computing checksum with sha256sum
Checksums matched!
Now using node v12.16.1 (npm v6.13.4)
Creating default alias: default -> 12.16.1 (-> v12.16.1)
root ➜ /Prebid.js (master) $ nvm use
Found '/Prebid.js/.nvmrc' with version <12.16.1>
Now using node v12.16.1 (npm v6.13.4)
root ➜ /Prebid.js (master) $ npm install gulp-cli -g
/usr/local/share/nvm/versions/node/v12.16.1/bin/gulp -> /usr/local/share/nvm/versions/node/v12.16.1/lib/node_modules/gulp-cli/bin/gulp.js
+ gulp-cli@3.0.0
added 80 packages from 71 contributors in 4.453s
root ➜ /Prebid.js (master) $ npm ci
[...]
> geckodriver@4.3.1 postinstall /Prebid.js/node_modules/geckodriver
> test -f ./dist/install.js && node ./dist/install.js || echo "Skipping install, project not build!"

internal/modules/cjs/loader.js:1174
      throw new ERR_REQUIRE_ESM(filename, parentPath, packageJsonPath);
      ^

Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: /Prebid.js/node_modules/geckodriver/dist/install.js
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1174:13)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)
    at internal/main/run_main_module.js:18:47 {
  code: 'ERR_REQUIRE_ESM'
}
Skipping install, project not build!

> edgedriver@5.3.9 install /Prebid.js/node_modules/edgedriver
> test -f ./dist/install.js && node ./dist/install.js || echo "Skipping install, project not build!"

internal/modules/cjs/loader.js:1174
      throw new ERR_REQUIRE_ESM(filename, parentPath, packageJsonPath);
      ^

Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: /Prebid.js/node_modules/edgedriver/dist/install.js
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1174:13)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)
    at internal/main/run_main_module.js:18:47 {
  code: 'ERR_REQUIRE_ESM'
}
Skipping install, project not build!
added 2334 packages in 11.686s


   ╭────────────────────────────────────────────────────────────────╮
   │                                                                │
   │      New major version of npm available! 6.13.4 -> 10.5.1      │
   │   Changelog: https://github.com/npm/cli/releases/tag/v10.5.1   │
   │               Run npm install -g npm to update!                │
   │                                                                │
   ╰────────────────────────────────────────────────────────────────╯

root ➜ /Prebid.js (master) $ gulp lint
/Prebid.js/webpack.conf.js:139
              return module.resource?.startsWith(core) || module.resource?.startsWith(nodeModules);
                                     ^

SyntaxError: Unexpected token '.'
    at wrapSafe (internal/modules/cjs/loader.js:1072:16)
    at Module._compile (internal/modules/cjs/loader.js:1122:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14)
    at Module.require (internal/modules/cjs/loader.js:1044:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (/Prebid.js/gulpfile.js:13:21)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
root ➜ /Prebid.js (master) $ 
```

The `npm ci` command finish with a success status code (0) but with two similar errors and with the message: "Skipping install, project not build!". Finally, the `gulp` commands (all of them) fail with the same error...

## Platform details

Is try to use the latest git version of Prebid.js.
I use ArchLinux Linux distribution, with docker.
```bash
root ➜ /Prebid.js (master) $ node --version
v12.16.1
root ➜ /Prebid.js (master) $ npm --version
6.13.4
root ➜ /Prebid.js (master) $ gulp --version
CLI version: 3.0.0
Local version: 4.0.2
```

**Comment by AlexisBRENON** [comment]
It seems to be a version mismatch error.
Adding an `nvm install node` step before any `npm ...` step fix the issue. This results in the following versions:
```bash
root ➜ /Prebid.js (master) $ node --version
v21.7.2
root ➜ /Prebid.js (master) $ npm --version
10.5.0
root ➜ /Prebid.js (master) $ gulp --version
CLI version: 3.0.0
Local version: 4.0.2
```
