### ISSUE TITLE
Error: Writable stream closed prematurely

### ISSUE THREAD

**Issue by rochapablo** [prebid/Prebid.js#11409]
## Description

`$ gulp build --modules=modules.json` it's not working

### Actual results

```
gulp build --modules=modules.json
[14:58:47] Using gulpfile ~/bitbucket/prebid.js/gulpfile.js
[14:58:47] Starting 'build'...
[14:58:47] Starting 'clean'...
[14:58:47] Finished 'clean' after 7.08 ms
[14:58:47] Starting 'build-bundle-prod'...
[14:58:47] Starting 'build-creative-prod'...
[14:58:47] Starting '<anonymous>'...
[14:58:48] asset renderers/native.js 1.81 KiB [emitted] [minimized] (name: renderers/native)
asset creative.js 1.21 KiB [emitted] [minimized] (name: creative)
asset renderers/display.js 254 bytes [emitted] [minimized] (name: renderers/display)

webpack 5.91.0 compiled successfully
[14:58:48] '<anonymous>' errored after 366 ms
[14:58:48] Error: Writable stream closed prematurely
    at Pipeline.done (/node_modules/streamx/index.js:444:43)
    at Stream.emit (node:events:513:28)
    at Stream.emit (node:domain:552:15)
    at Stream.stream.destroy (/node_modules/through/index.js:84:12)
    at /node_modules/through/index.js:59:16
    at processTicksAndRejections (node:internal/process/task_queues:78:11)
[14:58:48] 'build-creative-prod' errored after 366 ms
[14:58:48] 'build-bundle-prod' errored after 367 ms
[14:58:48] 'build' errored after 375 ms
```

## Platform details

MacOS
npm 8.19.3
node v16.19.1

**Comment by rochapablo** [comment]
Running from master version did work.
