### ISSUE TITLE
PubGears Unit Tests Fail on IE

### ISSUE THREAD

**Issue by dbemiller** [prebid/Prebid.js#1360]
## Type of issue
Bug

## Description
This has been happening for a long time... but I found the root cause while working on #1355, after fixing the source-maps so that I could see line numbers.

The PubGears unit tests use `CustomEvent`, which [isn't supported on IE](https://developer.mozilla.org/en-US/docs/Web/API/CustomEvent/CustomEvent).

These test failures make Prebid releases harder to validate, and prevent us from automating them.

## Failed test output

```
5) should call bidManager.addBidResponse() when bid received
     PubGearsAdapter bids received
     TypeError: Object doesn't support this action
   at Anonymous function (webpack:///test/spec/modules/pubgearsBidAdapter_spec.js:202:6 <- test/spec/modules/pubgearsBidAdapter_spec.js:2615:7)

6) should send correct bid response object when receiving onBidResponse event
     PubGearsAdapter bids received
     TypeError: Object doesn't support this action
   at Anonymous function (webpack:///test/spec/modules/pubgearsBidAdapter_spec.js:238:6 <- test/spec/modules/pubgearsBidAdapter_spec.js:2651:7)

7) should send $0 bid as no-bid response
     PubGearsAdapter bids received
     TypeError: Object doesn't support this action
   at Anonymous function (webpack:///test/spec/modules/pubgearsBidAdapter_spec.js:276:6 <- test/spec/modules/pubgearsBidAdapter_spec.js:2689:7)
```

**Comment by dbemiller** [comment]
@Walexander Please look into these when you get the chance.

**Comment by matthewlane** [comment]
Closing with Pubgears adapter and test not in 1.x
