### ISSUE TITLE
Pubgears adapter tests failing in IE browser

### ISSUE THREAD

**Issue by jaiminpanchal27** [prebid/Prebid.js#1519]
## Type of issue
Bug

## Description
Pubgears adapter tests are failing in IE browsers.`CustomEvent` is not supported in IE browsers.
```
  PubGearsAdapter
    bids received
      ✗ should call bidManager.addBidResponse() when bid received
	TypeError: Object doesn't support this action
	   at Anonymous function (webpack:///test/spec/modules/pubgearsBidAdapter_spec.js:202:6 <- test/spec/modules/pubgearsBidAdapter_spec.js:2840:7)

      ✗ should send correct bid response object when receiving onBidResponse event
	TypeError: Object doesn't support this action
	   at Anonymous function (webpack:///test/spec/modules/pubgearsBidAdapter_spec.js:238:6 <- test/spec/modules/pubgearsBidAdapter_spec.js:2876:7)

      ✗ should send $0 bid as no-bid response
	TypeError: Object doesn't support this action
	   at Anonymous function (webpack:///test/spec/modules/pubgearsBidAdapter_spec.js:276:6 <- test/spec/modules/pubgearsBidAdapter_spec.js:2914:7)
```

## Steps to reproduce
Run tests in IE.
`gulp test --watch --browsers=Chrome`
Copy karma url and run tests in IE.

### Expected results
All tests should pass.

### Actual results
Failing tests

## Other information
@Walexander

**Comment by dbemiller** [comment]
Duplicates #1360
