### ISSUE TITLE
thoughtleadr adapter tests failing in IE browsers

### ISSUE THREAD

**Issue by jaiminpanchal27** [prebid/Prebid.js#1521]
## Type of issue
Bug

## Description
Tests failing in IE browsers. 
```
  thoughtleadr adapter tests
    requestPlacement
      ✗ should sync cookies
	TypeError: Unable to set property 'innerHTML' of undefined or null reference
	   at writeFriendlyFrame (webpack:///modules/thoughtleadrBidAdapter.js:75:2 <- test/spec/modules/thoughtleadrBidAdapter_spec.js:3113:3)
	   at syncCookies (webpack:///modules/thoughtleadrBidAdapter.js:166:6 <- test/spec/modules/thoughtleadrBidAdapter_spec.js:3203:7)
	   at Anonymous function (webpack:///modules/thoughtleadrBidAdapter.js:127:8 <- test/spec/modules/thoughtleadrBidAdapter_spec.js:3164:9)
	   at Anonymous function (webpack:///test/spec/modules/thoughtleadrBidAdapter_spec.js:92:8 <- test/spec/modules/thoughtleadrBidAdapter_spec.js:3013:9)
	   at invoke (node_modules/sinon/pkg/sinon.js:2651:25)
	   at proxy (eval code:1:28)
	   at requestPlacement (webpack:///modules/thoughtleadrBidAdapter.js:124:4 <- test/spec/modules/thoughtleadrBidAdapter_spec.js:3161:5)
	   at callBids (webpack:///modules/thoughtleadrBidAdapter.js:115:6 <- test/spec/modules/thoughtleadrBidAdapter_spec.js:3152:7)
	   at Anonymous function (webpack:///test/spec/modules/thoughtleadrBidAdapter_spec.js:99:6 <- test/spec/modules/thoughtleadrBidAdapter_spec.js:3020:7)
```
These test failures make Prebid releases harder to validate, and prevent us from automating them.

## Other information
@ilya-pirogov

**Comment by matthewlane** [comment]
Closing with thoughtleadr adapter and test not in 1.x
