### ISSUE TITLE
Gulp Build : Command not working with the `--tag` option

### ISSUE THREAD

**Issue by ysfbsf** [prebid/Prebid.js#1569]
## Type of issue
This is a bug

## Description
The build command is not working when using the `--tag` to generate the Prebid file with a custom tag.

## Steps to reproduce
`$ gulp build --tag=v0.1_custom`

### Expected results
A `prebid.v0.1_custom.js` file generated

### Actual results
`
[12:35:40] Using gulpfile ~\Prebid\gulpfile.js
[12:35:40] Starting 'clean'...
[12:35:40] Finished 'clean' after 25 ms
[12:35:40] Starting 'webpack'...

internal/streams/legacy.js:59
      throw er; // Unhandled stream error in pipe.
      ^
Error: chunk roxotAnalyticsAdapter [initial]
prebid.v0.1_custom.js
Conflict: Multiple assets emit to the same filename prebid.v0.1_custom.js
Error: Conflict: Multiple assets emit to the same filename prebid.v0.1_custom.js
    at Compilation.createChunkAssets (C:\Users\Youssef\Desktop\Prebid\node_modules\webpack\lib\Compilation.js:1304:12)
    at sealPart2 (C:\Users\Youssef\Desktop\Prebid\node_modules\webpack\lib\Compilation.js:646:10)
    at Compilation.applyPluginsAsyncSeries (C:\Users\Youssef\Desktop\Prebid\node_modules\tapable\lib\Tapable.js:195:46)
    at Compilation.seal (C:\Users\Youssef\Desktop\Prebid\node_modules\webpack\lib\Compilation.js:596:8)
    at applyPluginsParallel.err (C:\Users\Youssef\Desktop\Prebid\node_modules\webpack\lib\Compiler.js:514:17)
    at C:\Users\Youssef\Desktop\Prebid\node_modules\tapable\lib\Tapable.js:289:11
    at _addModuleChain (C:\Users\Youssef\Desktop\Prebid\node_modules\webpack\lib\Compilation.js:498:11)
    at processModuleDependencies.err (C:\Users\Youssef\Desktop\Prebid\node_modules\webpack\lib\Compilation.js:468:14)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)chunk pulsepointAnalyticsAdapter [initial]
prebid.v0.1_custom.js
......
`

## Platform details
Prebid 0.28.1

**Comment by mkendall07** [comment]
@snapwich can you take a look at this?
