### ISSUE TITLE
prebidServerAdapter: Unit test fails in IE browser

### ISSUE THREAD

**Issue by jaiminpanchal27** [prebid/Prebid.js#1920]
## Type of issue
Bug

## Description
Test failures for prebidServerAdapter 
```
  S2S Adapter
    response handler
      ✗ does not call addBidResponse and calls done when ad unit not set
	AssertError: expected spy to be called once but was called 0 times
	   at fail (node_modules/sinon/pkg/sinon.js:6340:17)
	   at failAssertion (node_modules/sinon/pkg/sinon.js:6296:13)
	   at Anonymous function (node_modules/sinon/pkg/sinon.js:6321:21)
	   at Anonymous function (webpack:///test/spec/modules/prebidServerBidAdapter_spec.js:294:6 <- test/spec/modules/prebidServerBidAdapter_spec.js:12265:7)

      ✗ does not call addBidResponse and calls done when server requests cookie sync
	AssertError: expected spy to be called once but was called 0 times
	   at fail (node_modules/sinon/pkg/sinon.js:6340:17)
	   at failAssertion (node_modules/sinon/pkg/sinon.js:6296:13)
	   at Anonymous function (node_modules/sinon/pkg/sinon.js:6321:21)
	   at Anonymous function (webpack:///test/spec/modules/prebidServerBidAdapter_spec.js:305:6 <- test/spec/modules/prebidServerBidAdapter_spec.js:12276:7)

      ✗ does not call addBidResponse and calls done  when ad unit is set
	AssertError: expected spy to be called once but was called 0 times
	   at fail (node_modules/sinon/pkg/sinon.js:6340:17)
	   at failAssertion (node_modules/sinon/pkg/sinon.js:6296:13)
	   at Anonymous function (node_modules/sinon/pkg/sinon.js:6321:21)
	   at Anonymous function (webpack:///test/spec/modules/prebidServerBidAdapter_spec.js:316:6 <- test/spec/modules/prebidServerBidAdapter_spec.js:12287:7)

      ✗ registers successful bids and calls done when there are less bids than requests
	AssertError: expected spy to be called once but was called 0 times
	   at fail (node_modules/sinon/pkg/sinon.js:6340:17)
	   at failAssertion (node_modules/sinon/pkg/sinon.js:6296:13)
	   at Anonymous function (node_modules/sinon/pkg/sinon.js:6321:21)
	   at Anonymous function (webpack:///test/spec/modules/prebidServerBidAdapter_spec.js:327:6 <- test/spec/modules/prebidServerBidAdapter_spec.js:12298:7)
```

**Comment by jaiminpanchal27** [comment]
Fixed in #1918
