### ISSUE TITLE
Yieldbot test failures on IE/Edge

### ISSUE THREAD

**Issue by matthewlane** [prebid/Prebid.js#2229]
## Type of issue
- Test failures

## Description
Yieldbot changes introduced in #2135 are causing these test failures:

```
1) should set a root path first-party cookie with temporal expiry
     Yieldbot Adapter Unit Tests setCookie
     expected null to equal 'jegbe97m37hx7zhz3d'
Error
   at AssertionError (webpack:///node_modules/assertion-error/index.js:74:0 <- test/test_index.js:9131:7)
   at Assertion.prototype.assert (webpack:///node_modules/chai/lib/chai/assertion.js:107:0 <- test/test_index.js:14733:7)
   at assertEqual (webpack:///node_modules/chai/lib/chai/core/assertions.js:487:0 <- test/test_index.js:15250:7)
   at ctx[name] (webpack:///node_modules/chai/lib/chai/utils/addMethod.js:41:0 <- test/test_index.js:14320:5)
   at Anonymous function (webpack:///test/spec/modules/yieldbotBidAdapter_spec.js:444:6 <- test/test_index.js:61051:8)

2) should set a root path first-party cookie with session expiry
     Yieldbot Adapter Unit Tests setCookie
     expected null to equal 'jegbe986buwpu5oar5'
Error
   at AssertionError (webpack:///node_modules/assertion-error/index.js:74:0 <- test/test_index.js:9131:7)
   at Assertion.prototype.assert (webpack:///node_modules/chai/lib/chai/assertion.js:107:0 <- test/test_index.js:14733:7)
   at assertEqual (webpack:///node_modules/chai/lib/chai/core/assertions.js:487:0 <- test/test_index.js:15250:7)
   at ctx[name] (webpack:///node_modules/chai/lib/chai/utils/addMethod.js:41:0 <- test/test_index.js:14320:5)
   at Anonymous function (webpack:///test/spec/modules/yieldbotBidAdapter_spec.js:455:6 <- test/test_index.js:61062:8)

3) should delete all first-party cookies
     Yieldbot Adapter Unit Tests clearAllcookies
     sessionBlocked: expected false to equal true
Error
   at AssertionError (webpack:///node_modules/assertion-error/index.js:74:0 <- test/test_index.js:9131:7)
   at Assertion.prototype.assert (webpack:///node_modules/chai/lib/chai/assertion.js:107:0 <- test/test_index.js:14733:7)
   at assertEqual (webpack:///node_modules/chai/lib/chai/core/assertions.js:487:0 <- test/test_index.js:15250:7)
   at ctx[name] (webpack:///node_modules/chai/lib/chai/utils/addMethod.js:41:0 <- test/test_index.js:14320:5)
   at Anonymous function (webpack:///test/spec/modules/yieldbotBidAdapter_spec.js:478:6 <- test/test_index.js:61088:8)

4) should return true if cookie value is interpreted as non-zero
     Yieldbot Adapter Unit Tests sessionBlocked
     cookie value: the string "1": expected false to equal true
Error
   at AssertionError (webpack:///node_modules/assertion-error/index.js:74:0 <- test/test_index.js:9131:7)
   at Assertion.prototype.assert (webpack:///node_modules/chai/lib/chai/assertion.js:107:0 <- test/test_index.js:14733:7)
   at assertEqual (webpack:///node_modules/chai/lib/chai/core/assertions.js:487:0 <- test/test_index.js:15250:7)
   at ctx[name] (webpack:///node_modules/chai/lib/chai/utils/addMethod.js:41:0 <- test/test_index.js:14320:5)
   at Anonymous function (webpack:///test/spec/modules/yieldbotBidAdapter_spec.js:529:6 <- test/test_index.js:61139:8)

5) should set sessionBlocked
     Yieldbot Adapter Unit Tests sessionBlocked
     expected false to equal true
Error
   at AssertionError (webpack:///node_modules/assertion-error/index.js:74:0 <- test/test_index.js:9131:7)
   at Assertion.prototype.assert (webpack:///node_modules/chai/lib/chai/assertion.js:107:0 <- test/test_index.js:14733:7)
   at assertEqual (webpack:///node_modules/chai/lib/chai/core/assertions.js:487:0 <- test/test_index.js:15250:7)
   at ctx[name] (webpack:///node_modules/chai/lib/chai/utils/addMethod.js:41:0 <- test/test_index.js:14320:5)
   at Anonymous function (webpack:///test/spec/modules/yieldbotBidAdapter_spec.js:571:6 <- test/test_index.js:61181:8)

6) should return user Id if cookie exists
     Yieldbot Adapter Unit Tests userId
     expected 'jegbe9av9h4h1uzcru' to equal 'jegbe9avtrthrfyw0b'
Error
   at AssertionError (webpack:///node_modules/assertion-error/index.js:74:0 <- test/test_index.js:9131:7)
   at Assertion.prototype.assert (webpack:///node_modules/chai/lib/chai/assertion.js:107:0 <- test/test_index.js:14733:7)
   at assertEqual (webpack:///node_modules/chai/lib/chai/core/assertions.js:487:0 <- test/test_index.js:15250:7)
   at ctx[name] (webpack:///node_modules/chai/lib/chai/utils/addMethod.js:41:0 <- test/test_index.js:14320:5)
   at Anonymous function (webpack:///test/spec/modules/yieldbotBidAdapter_spec.js:607:6 <- test/test_index.js:61217:8)

7) should return session Id if cookie exists
     Yieldbot Adapter Unit Tests sessionId
     expected 'jegbe9boikwo6rmpww' to equal 'jegbe9bo50ttob85zl'
Error
   at AssertionError (webpack:///node_modules/assertion-error/index.js:74:0 <- test/test_index.js:9131:7)
   at Assertion.prototype.assert (webpack:///node_modules/chai/lib/chai/assertion.js:107:0 <- test/test_index.js:14733:7)
   at assertEqual (webpack:///node_modules/chai/lib/chai/core/assertions.js:487:0 <- test/test_index.js:15250:7)
   at ctx[name] (webpack:///node_modules/chai/lib/chai/utils/addMethod.js:41:0 <- test/test_index.js:14320:5)
   at Anonymous function (webpack:///test/spec/modules/yieldbotBidAdapter_spec.js:631:6 <- test/test_index.js:61241:8)

8) should set an id string
     Yieldbot Adapter Unit Tests lastPageviewId
     expected '' to equal 'jegbe9c4i59rqodjcj'
Error
   at AssertionError (webpack:///node_modules/assertion-error/index.js:74:0 <- test/test_index.js:9131:7)
   at Assertion.prototype.assert (webpack:///node_modules/chai/lib/chai/assertion.js:107:0 <- test/test_index.js:14733:7)
   at assertEqual (webpack:///node_modules/chai/lib/chai/core/assertions.js:487:0 <- test/test_index.js:15250:7)
   at ctx[name] (webpack:///node_modules/chai/lib/chai/utils/addMethod.js:41:0 <- test/test_index.js:14320:5)
   at Anonymous function (webpack:///test/spec/modules/yieldbotBidAdapter_spec.js:656:6 <- test/test_index.js:61266:8)

9) should set a timestamp
     Yieldbot Adapter Unit Tests lastPageviewTime
     expected 0 to equal 1520380670443
Error
   at AssertionError (webpack:///node_modules/assertion-error/index.js:74:0 <- test/test_index.js:9131:7)
   at Assertion.prototype.assert (webpack:///node_modules/chai/lib/chai/assertion.js:107:0 <- test/test_index.js:14733:7)
   at assertEqual (webpack:///node_modules/chai/lib/chai/core/assertions.js:487:0 <- test/test_index.js:15250:7)
   at ctx[name] (webpack:///node_modules/chai/lib/chai/utils/addMethod.js:41:0 <- test/test_index.js:14320:5)
   at Anonymous function (webpack:///test/spec/modules/yieldbotBidAdapter_spec.js:681:6 <- test/test_index.js:61291:8)

10) should increment the integer string for depth
     Yieldbot Adapter Unit Tests pageviewDepth
     expected 1 to equal 2
Error
   at AssertionError (webpack:///node_modules/assertion-error/index.js:74:0 <- test/test_index.js:9131:7)
   at Assertion.prototype.assert (webpack:///node_modules/chai/lib/chai/assertion.js:107:0 <- test/test_index.js:14733:7)
   at assertEqual (webpack:///node_modules/chai/lib/chai/core/assertions.js:487:0 <- test/test_index.js:15250:7)
   at ctx[name] (webpack:///node_modules/chai/lib/chai/utils/addMethod.js:41:0 <- test/test_index.js:14320:5)
   at Anonymous function (webpack:///test/spec/modules/yieldbotBidAdapter_spec.js:707:6 <- test/test_index.js:61317:8)

11) should return prefix if cookie exists
     Yieldbot Adapter Unit Tests urlPrefix
     expected '//i.yldbt.com/m/' to equal 'http://closest.az.com/path/'
Error
   at AssertionError (webpack:///node_modules/assertion-error/index.js:74:0 <- test/test_index.js:9131:7)
   at Assertion.prototype.assert (webpack:///node_modules/chai/lib/chai/assertion.js:107:0 <- test/test_index.js:14733:7)
   at assertEqual (webpack:///node_modules/chai/lib/chai/core/assertions.js:487:0 <- test/test_index.js:15250:7)
   at ctx[name] (webpack:///node_modules/chai/lib/chai/utils/addMethod.js:41:0 <- test/test_index.js:14320:5)
   at Anonymous function (webpack:///test/spec/modules/yieldbotBidAdapter_spec.js:728:6 <- test/test_index.js:61338:8)

12) should reset prefix if default already set
     Yieldbot Adapter Unit Tests urlPrefix
     subsequent request: expected '//i.yldbt.com/m/' to equal 'http://close.az.com/path/'
Error
   at AssertionError (webpack:///node_modules/assertion-error/index.js:74:0 <- test/test_index.js:9131:7)
   at Assertion.prototype.assert (webpack:///node_modules/chai/lib/chai/assertion.js:107:0 <- test/test_index.js:14733:7)
   at assertEqual (webpack:///node_modules/chai/lib/chai/core/assertions.js:487:0 <- test/test_index.js:15250:7)
   at ctx[name] (webpack:///node_modules/chai/lib/chai/utils/addMethod.js:41:0 <- test/test_index.js:14320:5)
   at Anonymous function (webpack:///test/spec/modules/yieldbotBidAdapter_spec.js:740:6 <- test/test_index.js:61350:8)

13) should not return bid requests if sessionBlocked
     Yieldbot Adapter Unit Tests buildRequests
     expected 1 to equal 0
Error
   at AssertionError (webpack:///node_modules/assertion-error/index.js:74:0 <- test/test_index.js:9131:7)
   at Assertion.prototype.assert (webpack:///node_modules/chai/lib/chai/assertion.js:107:0 <- test/test_index.js:14733:7)
   at assertEqual (webpack:///node_modules/chai/lib/chai/core/assertions.js:487:0 <- test/test_index.js:15250:7)
   at ctx[name] (webpack:///node_modules/chai/lib/chai/utils/addMethod.js:41:0 <- test/test_index.js:14320:5)
   at Anonymous function (webpack:///test/spec/modules/yieldbotBidAdapter_spec.js:829:6 <- test/test_index.js:61412:8)

14) should re-enable requests when sessionBlocked expires
     Yieldbot Adapter Unit Tests buildRequests
     expected 1 to equal 0
Error
   at AssertionError (webpack:///node_modules/assertion-error/index.js:74:0 <- test/test_index.js:9131:7)
   at Assertion.prototype.assert (webpack:///node_modules/chai/lib/chai/assertion.js:107:0 <- test/test_index.js:14733:7)
   at assertEqual (webpack:///node_modules/chai/lib/chai/core/assertions.js:487:0 <- test/test_index.js:15250:7)
   at ctx[name] (webpack:///node_modules/chai/lib/chai/utils/addMethod.js:41:0 <- test/test_index.js:14320:5)
   at Anonymous function (webpack:///test/spec/modules/yieldbotBidAdapter_spec.js:841:6 <- test/test_index.js:61420:8)

15) should use edge server Url prefix if set
     Yieldbot Adapter Unit Tests buildRequests
     expected '//i.yldbt.com/m/1234/v1/init' to match /^http:\/\/close\.edge\.adserver\.com\//
Error
   at AssertionError (webpack:///node_modules/assertion-error/index.js:74:0 <- test/test_index.js:9131:7)
   at Assertion.prototype.assert (webpack:///node_modules/chai/lib/chai/assertion.js:107:0 <- test/test_index.js:14733:7)
   at assertMatch (webpack:///node_modules/chai/lib/chai/core/assertions.js:1074:0 <- test/test_index.js:15837:5)
   at ctx[name] (webpack:///node_modules/chai/lib/chai/utils/addMethod.js:41:0 <- test/test_index.js:14320:5)
   at Anonymous function (webpack:///test/spec/modules/yieldbotBidAdapter_spec.js:962:6 <- test/test_index.js:61511:8)

16) should set edge server Url prefix
     Yieldbot Adapter Unit Tests interpretResponse
     expected null to match /^http:\/\/close.edge.adserver.com\//
Error
   at AssertionError (webpack:///node_modules/assertion-error/index.js:74:0 <- test/test_index.js:9131:7)
   at Assertion.prototype.assert (webpack:///node_modules/chai/lib/chai/assertion.js:107:0 <- test/test_index.js:14733:7)
   at assertMatch (webpack:///node_modules/chai/lib/chai/core/assertions.js:1074:0 <- test/test_index.js:15837:5)
   at ctx[name] (webpack:///node_modules/chai/lib/chai/utils/addMethod.js:41:0 <- test/test_index.js:14320:5)
   at Anonymous function (webpack:///test/spec/modules/yieldbotBidAdapter_spec.js:1059:6 <- test/test_index.js:61587:8)

17) should use server response url_prefix property value after the first auction
     Yieldbot Adapter Unit Tests Adapter Auction Behavior
     Locality url prefix: expected '//i.yldbt.com/m/1234/v1/init?cts_js=1520380668615&cts_ns=1520380668615&v=pbjs-yb-0.0.1&vi=jegbe9l05peqb3rdk8&si=jegbe9l0wd7eas2lqz&pvd=1&pvi=jegbe9l02gkj72nkxn&lpv=0&lpvi=&bt=refresh&ua=Mozilla%2F5.0%20(Windows%20NT%2010.0%3B%20WOW64%3B%20Trident%2F7.0%3B%20.NET4.0C%3B%20.NET4.0E%3B%20.NET%20CLR%202.0.50727%3B%20.NET%20CLR%203.0.30729%3B%20.NET%20CLR%203.5.30729%3B%20rv%3A11.0)%20like%20Gecko&np=Win32&la=en-US&to=5&sd=1024x768&lo=http%3A%2F%2Flocalhost%3A9876%2F%3Fid%3D72946554&r=&e=&sn=leaderboard%7Cmedrec%7Cskyscraper&ssz=728x90%7C300x250.300x600%7C160x600&cts_ini=1520380670725&' to match /ads-adseast-vpc\.yldbt\.com\/m\//
Error
   at AssertionError (webpack:///node_modules/assertion-error/index.js:74:0 <- test/test_index.js:9131:7)
   at Assertion.prototype.assert (webpack:///node_modules/chai/lib/chai/assertion.js:107:0 <- test/test_index.js:14733:7)
   at assertMatch (webpack:///node_modules/chai/lib/chai/core/assertions.js:1074:0 <- test/test_index.js:15837:5)
   at ctx[name] (webpack:///node_modules/chai/lib/chai/utils/addMethod.js:41:0 <- test/test_index.js:14320:5)
   at Anonymous function (webpack:///test/spec/modules/yieldbotBidAdapter_spec.js:1279:6 <- test/test_index.js:61791:8)

18) should increment the session page view depth only before the first auction
     Yieldbot Adapter Unit Tests Adapter Auction Behavior
     Second visit, first pvd: expected '1' to equal '2'
Error
   at AssertionError (webpack:///node_modules/assertion-error/index.js:74:0 <- test/test_index.js:9131:7)
   at Assertion.prototype.assert (webpack:///node_modules/chai/lib/chai/assertion.js:107:0 <- test/test_index.js:14733:7)
   at assertEqual (webpack:///node_modules/chai/lib/chai/core/assertions.js:487:0 <- test/test_index.js:15250:7)
   at ctx[name] (webpack:///node_modules/chai/lib/chai/utils/addMethod.js:41:0 <- test/test_index.js:14320:5)
   at Anonymous function (webpack:///test/spec/modules/yieldbotBidAdapter_spec.js:1318:6 <- test/test_index.js:61830:8)
```

on these platforms:
```
- Edge 14.14393.0 (Windows 10.0.0)
- IE 11.0.0 (Windows 10.0.0)
- IE 11.0.0 (Windows 8.1.0.0)
- IE 11.0.0 (Windows 7.0.0)
```

Tests pass on all other platforms defined in [browsers.json](https://github.com/prebid/Prebid.js/blob/master/browsers.json)

## Platform details
- Prebid 1.5.0-pre
- Node 9.7.1
- Tested via Browserstack and the browsers defined in  [browsers.json](https://github.com/prebid/Prebid.js/blob/master/browsers.json) with:
`gulp test --browserstack`

## Other information
@elljoh @solenoid please review

**Comment by elljoh** [comment]
Thanks @matthewlane. Please assign to me. I will look into reproducing this.
