### ISSUE TITLE
InvibesBidAdapter unit test failing in Edge 14 browser

### ISSUE THREAD

**Issue by jsnellbaker** [prebid/Prebid.js#2339]
## Type of issue
Bug/Issue

## Description
While running our browserstack tests for the prebid release process, we encountered this consistent error in the `InvibesBidAdapter` file for the Edge 14 browser.  

It seems like there is a cookie that shouldn't be present for this unit test.  @rcheptanariu Could you take a look and see if there are any changes that could be made to the unit test? 
 
```
invibesBidAdapter:
    buildRequests
      ✗ uses cookies
	expected 'p4rrk7.ax2i2s' to be undefined
	Error
	   at AssertionError (webpack:///node_modules/assertion-error/index.js:74:0 <- test/test_index.js:9276:7)
	   at Assertion.prototype.assert (webpack:///node_modules/chai/lib/chai/assertion.js:107:0 <- test/test_index.js:14898:7)
	   at Anonymous function (webpack:///node_modules/chai/lib/chai/core/assertions.js:343:0 <- test/test_index.js:15271:5)
	   at addProperty (webpack:///node_modules/chai/lib/chai/utils/addProperty.js:43:0 <- test/test_index.js:14433:9)
	   at Anonymous function (webpack:///test/spec/modules/invibesBidAdapter_spec.js:120:6 <- test/test_index.js:40491:8)
```

**Comment by jaiminpanchal27** [comment]
This bug is fixed, have not seen this popup recently in our test logs
