### ISSUE TITLE
Test failure: triplelift adapter "before each" hook FAILED

### ISSUE THREAD

**Issue by ptim** [prebid/Prebid.js#2382]
## Type of issue

Test failure on legacy branch (0.34.8-pre)

## Description

FYI - see actual results, below

## Steps to reproduce

- checkout the 'legacy' branch, (#5eb680c)
- `yarn install`
- `gulp serve`

## Test page

NA

### Expected results

Tests pass

### Actual results

```
HeadlessChrome 65.0.3325 (Mac OS X 10.12.6): Executed 878 of 1798 SUCCESS (0 secs / 0.523 secs)
HeadlessChrome 65.0.3325 (Mac OS X 10.12.6) triplelift adapter "before each" hook FAILED
	Error: Uncaught TypeError: Fake XHR onreadystatechange handler threw exception: Cannot read property 'seatbid' of undefined (node_modules/sinon/pkg/sinon.js:4469)
HeadlessChrome 65.0.3325 (Mac OS X 10.12.6): Executed 1390 of 1798 (1 FAILED) (24.484 secs / 0.862 secs)
[13:07:06] 'test' errored after 1.9 min
[13:07:06] Error: Karma tests failed with exit code 1
    at ~/Prebid.js/gulpfile.js:120:12
    at removeAllListeners (~/Prebid.js/node_modules/karma/lib/server.js:380:7)
    at Server.<anonymous> (~/Prebid.js/node_modules/karma/lib/server.js:391:9)
    at Server.g (events.js:291:16)
    at emitNone (events.js:91:20)
    at Server.emit (events.js:185:7)
    at emitCloseNT (net.js:1558:8)
    at _combinedTickCallback (internal/process/next_tick.js:77:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
```

## Platform details

OSX 10.12.6 
Node 6.10.2 via NVM

**Comment by snapwich** [comment]
@ptim just opened a pull-request that I think will alleviate these issues
