### ISSUE TITLE
Find and update package.json for issue with fresh install

### ISSUE THREAD

**Issue by mkendall07** [prebid/Prebid.js#2948]
a fresh install running gulp serve results in this error:
```
module.js:549
    throw err;
    ^

Error: Cannot find module '../build/tries/current/icann.complete.json'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
```
Seems related to 
https://github.com/peerigon/parse-domain/issues/35

We should update dependencies to resolve.

**Comment by mkendall07** [comment]
this solves the issue
>npm install pvdlg/parse-domain#overwrite-tries --save
