### ISSUE TITLE
Update Minimum Node version

### ISSUE THREAD

**Issue by scottalan** [prebid/Prebid.js#3055]
## Type of issue

Bug

## Description

package.json shows:

```
"engines": {
    "node": ">=4.0"
  },
```
but should probably be:

```
"engines": {
    "node": ">=6.0"
  },
```

Error running: `gulp build-bundle-dev` (see Actual results)

The node version requirement:
https://github.com/prebid/Prebid.js/blob/1.23.0/package.json#L24

Support:
https://node.green/#ES2016-features-Array-prototype-includes

## Steps to reproduce

Install node v4.8.3 and npm v5.6.0
Run: `npx gulp build-bundle-dev --modules=ixBidAdapter,openxBidAdapter,rubiconBidAdapter`

### Expected results
Gulp compiles the prebid.js file in build/dev

### Actual results

```
npx gulp build-bundle-dev --modules=ixBidAdapter,openxBidAdapter,rubiconBidAdapter
[20:01:20] Using gulpfile /var/www/build/html/sites/all/modules/contrib/dfp/prebid/js/prebid/gulpfile.js
[20:01:20] Starting 'clean'...
[20:01:20] Finished 'clean' after 25 ms
[20:01:20] Starting 'devpack'...
/var/www/build/html/sites/all/modules/contrib/dfp/prebid/js/prebid/webpack.conf.js:91
        return !(count < 2 || neverBundle.includes(path.basename(module.resource)))
                                          ^

TypeError: neverBundle.includes is not a function
    at module.exports.module.plugins.webpack.optimize.CommonsChunkPlugin.minChunks (/var/www/build/html/sites/all/modules/contrib/dfp/prebid/js/prebid/webpack.conf.js:91:43)
    at /var/www/build/html/sites/all/modules/contrib/dfp/prebid/js/prebid/node_modules/webpack/lib/optimize/CommonsChunkPlugin.js:338:11
    at Array.filter (native)
    at CommonsChunkPlugin.getExtractableModules (/var/www/build/html/sites/all/modules/contrib/dfp/prebid/js/prebid/node_modules/webpack/lib/optimize/CommonsChunkPlugin.js:334:46)
    at /var/www/build/html/sites/all/modules/contrib/dfp/prebid/js/prebid/node_modules/webpack/lib/optimize/CommonsChunkPlugin.js:139:38
    at Array.forEach (native)
    at Compilation.<anonymous> (/var/www/build/html/sites/all/modules/contrib/dfp/prebid/js/prebid/node_modules/webpack/lib/optimize/CommonsChunkPlugin.js:105:18)
    at Compilation.applyPluginsBailResult1 (/var/www/build/html/sites/all/modules/contrib/dfp/prebid/js/prebid/node_modules/webpack/node_modules/tapable/lib/Tapable.js:140:27)
    at Compilation.seal (/var/www/build/html/sites/all/modules/contrib/dfp/prebid/js/prebid/node_modules/webpack/lib/Compilation.js:604:9)
    at /var/www/build/html/sites/all/modules/contrib/dfp/prebid/js/prebid/node_modules/webpack/lib/Compiler.js:504:17
    at /var/www/build/html/sites/all/modules/contrib/dfp/prebid/js/prebid/node_modules/webpack/node_modules/tapable/lib/Tapable.js:289:11
    at /var/www/build/html/sites/all/modules/contrib/dfp/prebid/js/prebid/node_modules/webpack/lib/Compilation.js:511:11
    at /var/www/build/html/sites/all/modules/contrib/dfp/prebid/js/prebid/node_modules/webpack/lib/Compilation.js:481:14
    at nextTickCallbackWith0Args (node.js:489:9)
    at process._tickCallback (node.js:418:13)
```

## Platform details

Prebid.js v1.23.0
Chrome
Mac OS / Docker (centos)
node --version : v4.8.3
npm --version : 5.6.0

**Comment by ZLester** [comment]
There are only two occurrences of `.includes` in the build process that break compatibility with v4.0.0 – I'd probably advocate for their replacement with an equivalent `.indexOf` to maintain compatibility with a wider range of Node versions (including lts/argon) rather than bumping up requirements.
