### ISSUE TITLE
AppNexus Outstream and unfriendly Iframe

### ISSUE THREAD

**Issue by phtechno** [prebid/Prebid.js#3358]
## Type of issue
Bug

## Description
We use unfriendly Iframes to integrate prebid on our pages. The Bidding mechanism is on a subdomain of the parent page. The rendered creatives are also on the subdomain. For the communication for this frames we use postmessages.
For normal display ads it works. But for AppNexus video outstream ads the renderer-player (https://acdn.adnxs.com/video/outstream/ANOutstreamVideo.js) wants to access the parent page. Because of the Cross-Domain-Frames it is not possible.

_ANOutstreamVideo.js:54 Uncaught DOMException: Blocked a frame with origin "https://example.com" from accessing a cross-origin frame.
    at Object.<anonymous> (https://acdn.adnxs.com/video/outstream/ANOutstreamVideo.js:54:7314)
    at t (https://acdn.adnxs.com/video/outstream/ANOutstreamVideo.js:41:127)
    at Object.<anonymous> (https://acdn.adnxs.com/video/outstream/ANOutstreamVideo.js:51:26548)
    at t (https://acdn.adnxs.com/video/outstream/ANOutstreamVideo.js:41:127)
    at Object.<anonymous> (https://acdn.adnxs.com/video/outstream/ANOutstreamVideo.js:41:5480)
    at t (https://acdn.adnxs.com/video/outstream/ANOutstreamVideo.js:41:127)
    at Object.<anonymous> (https://acdn.adnxs.com/video/outstream/ANOutstreamVideo.js:41:4973)
    at t (https://acdn.adnxs.com/video/outstream/ANOutstreamVideo.js:41:127)
    at https://acdn.adnxs.com/video/outstream/ANOutstreamVideo.js:41:214
    at https://acdn.adnxs.com/video/outstream/ANOutstreamVideo.js:41:219_

## Steps to reproduce
Integrate prebid like above.

### Expected results
The AppNexus Renderer don't want to access the parent page

### Actual results
The AppNexus Renderer want to access the parent page and so the player doesn't work.

## Platform details
Tested on Chrome and Firefox with Prebid v1.32.0

**Comment by mkendall07** [comment]
this is a fairly uncommon setup so we'll probably not support it anytime soon. Going to close this as it's an expected limitation.
