### ISSUE TITLE
Build from source

### ISSUE THREAD

**Issue by JCarterGw** [prebid/Prebid.js#397]
Following the given instructions https://github.com/prebid/Prebid.js/#build
with node-v4.4.5 installed I am not able to build Prebid.js-0.9.2. The following error is generated:

/home/george/pre/Prebid.js-0.9.2/webpack.conf.js:42
                   return `${prebid.repository.url.split('/')[3]}_prebid_${prebid
                             ^
SyntaxError: Unexpected token ILLEGAL
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/george/pre/Prebid.js-0.9.2/gulpfile.js:13:21)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Liftoff.handleArguments (/usr/local/lib/node_modules/gulp/bin/gulp.js:116:3)
    at Liftoff.<anonymous> (/usr/local/lib/node_modules/gulp/node_modules/liftoff/index.js:193:16)
    at module.exports (/usr/local/lib/node_modules/gulp/node_modules/liftoff/node_modules/flagged-respawn/index.js:17:3)

Note: environment is ubuntu 14.04

**Comment by JCarterGw** [comment]
Resolved: I was using older versions of nodejs/gulp.
