### ISSUE TITLE
CI jobs failing

### ISSUE THREAD

**Issue by pm-harshad-mane** [prebid/Prebid.js#4589]
Hi
The CI job is failing due to the following two test failures:

a PR is blocked due to this, https://github.com/prebid/Prebid.js/pull/4588
CI job details: https://app.circleci.com/jobs/github/prebid/Prebid.js/5457

Error
   at AssertionError (webpack:///node_modules/assertion-error/index.js:74 <- test/test_index.js:40669:7)
   at Assertion.prototype.assert (webpack:///node_modules/chai/lib/chai/assertion.js:141 <- test/test_index.js:54928:7)
   at assertEql (webpack:///node_modules/chai/lib/chai/core/assertions.js:1083 <- test/test_index.js:56041:5)
   at methodWrapper (webpack:///node_modules/chai/lib/chai/utils/addMethod.js:57 <- test/test_index.js:54058:5)
   at assertEqual (webpack:///node_modules/chai/lib/chai/core/assertions.js:1023 <- test/test_index.js:55981:7)
   at methodWrapper (webpack:///node_modules/chai/lib/chai/utils/addMethod.js:57 <- test/test_index.js:54058:5)
   at Anonymous function (webpack:///test/spec/tpmnBidAdapter_spec.js:81:6 <- test/test_index.js:281576:7)

[21:42:24] 'test' errored after 2.55 min
[21:42:24] Error: Karma tests failed with exit code 1
    at /home/circleci/Prebid.js/gulpfile.js:278:12
    at removeAllListeners (/home/circleci/Prebid.js/node_modules/karma/lib/server.js:354:9)
    at webServer.close (/home/circleci/Prebid.js/node_modules/karma/lib/server.js:365:13)
    at Server.close (net.js:1604:9)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:111:20)
    at Server.emit (events.js:208:7)
    at emitCloseNT (net.js:1655:8)
    at _combinedTickCallback (internal/process/next_tick.js:135:11)
    at process._tickDomainCallback (internal/process/next_tick.js:218:9)
[21:42:24] 'test' errored after 2.88 min
Exited with code exit status 1
CircleCI received exit code 1

**Comment by jsnellbaker** [comment]
https://github.com/prebid/Prebid.js/pull/4594 This PR should help address some of the recent test failures we've been seeing with browserstack/circleci.

**Comment by pm-harshad-mane** [comment]
Thank you @jsnellbaker it worked !!
