### ISSUE TITLE
gulp test-coverage throws an error

### ISSUE THREAD

**Issue by florin-nedelcu** [prebid/Prebid.js#5245]
## Description
The command gulp test works fine and all tests are passing. When running test-coverage the following error occurs:
[15:34:25] Using gulpfile ~\Desktop\prebid\Prebid.js\gulpfile.js
[15:34:25] Starting 'test-coverage'...
[15:34:25] Starting 'clean'...
[15:34:25] Finished 'clean' after 168 ms
[15:34:25] Starting 'testCoverage'...
i ｢wdm｣:
i ｢wdm｣: Compiled successfully.

START:
i ｢wdm｣: Compiling...
i ｢wdm｣:
i ｢wdm｣: Compiled successfully.
15 05 2020 15:35:46.414:INFO [karma-server]: Karma v4.4.1 server started at http://0.0.0.0:9876/
15 05 2020 15:35:46.416:INFO [launcher]: Launching browsers ChromeHeadless with concurrency 5
15 05 2020 15:35:46.942:INFO [launcher]: Starting browser ChromeHeadless
15 05 2020 15:35:49.109:INFO [HeadlessChrome 81.0.4044 (Windows 10.0.0)]: Connected on socket -M8ziOESPCSLyKq8AAAA with id 87397791
15 05 2020 15:35:53.538:WARN [reporter]: SourceMap position not found for trace: Uncaught TypeError: Cannot read property 'f' of undefinedat http://localhost:9876/base/test/test_index.js?e9733d491ba8dd8e6ccd1b6ec57c2b43b90d0eb9:179:185055

TypeError: Cannot read property 'f' of undefined
    at Object.getParameterByName (http://localhost:9876/base/test/test_index.js?e9733d491ba8dd8e6ccd1b6ec57c2b43b90d0eb9:179:185055)
    at Object.<anonymous> (http://localhost:9876/base/test/test_index.js?e9733d491ba8dd8e6ccd1b6ec57c2b43b90d0eb9:248:55165)
    at __webpack_require__ (http://localhost:9876/base/test/test_index.js?e9733d491ba8dd8e6ccd1b6ec57c2b43b90d0eb9:20:30)
    at Object.<anonymous> (http://localhost:9876/base/test/test_index.js?e9733d491ba8dd8e6ccd1b6ec57c2b43b90d0eb9:166:69)
    at __webpack_require__ (http://localhost:9876/base/test/test_index.js?e9733d491ba8dd8e6ccd1b6ec57c2b43b90d0eb9:20:30)
    at Object.<anonymous> (http://localhost:9876/base/test/test_index.js?e9733d491ba8dd8e6ccd1b6ec57c2b43b90d0eb9:873:68)
    at __webpack_require__ (http://localhost:9876/base/test/test_index.js?e9733d491ba8dd8e6ccd1b6ec57c2b43b90d0eb9:20:30)
    at Object.<anonymous> (http://localhost:9876/base/test/test_index.js?e9733d491ba8dd8e6ccd1b6ec57c2b43b90d0eb9:13301:74)
    at __webpack_require__ (http://localhost:9876/base/test/test_index.js?e9733d491ba8dd8e6ccd1b6ec57c2b43b90d0eb9:20:30)
    at Object.<anonymous> (http://localhost:9876/base/test/test_index.js?e9733d491ba8dd8e6ccd1b6ec57c2b43b90d0eb9:34003:1)
15 05 2020 15:35:53.541:WARN [reporter]: SourceMap position not found for trace: Uncaught TypeError: Cannot read property 'f' of undefinedat http://localhost:9876/base/test/test_index.js?e9733d491ba8dd8e6ccd1b6ec57c2b43b90d0eb9:179:185055

TypeError: Cannot read property 'f' of undefined
    at Object.getParameterByName (http://localhost:9876/base/test/test_index.js?e9733d491ba8dd8e6ccd1b6ec57c2b43b90d0eb9:179:185055)
    at Object.<anonymous> (http://localhost:9876/base/test/test_index.js?e9733d491ba8dd8e6ccd1b6ec57c2b43b90d0eb9:248:55165)
    at __webpack_require__ (http://localhost:9876/base/test/test_index.js?e9733d491ba8dd8e6ccd1b6ec57c2b43b90d0eb9:20:30)
    at Object.<anonymous> (http://localhost:9876/base/test/test_index.js?e9733d491ba8dd8e6ccd1b6ec57c2b43b90d0eb9:166:69)
    at __webpack_require__ (http://localhost:9876/base/test/test_index.js?e9733d491ba8dd8e6ccd1b6ec57c2b43b90d0eb9:20:30)
    at Object.<anonymous> (http://localhost:9876/base/test/test_index.js?e9733d491ba8dd8e6ccd1b6ec57c2b43b90d0eb9:873:68)
    at __webpack_require__ (http://localhost:9876/base/test/test_index.js?e9733d491ba8dd8e6ccd1b6ec57c2b43b90d0eb9:20:30)
    at Object.<anonymous> (http://localhost:9876/base/test/test_index.js?e9733d491ba8dd8e6ccd1b6ec57c2b43b90d0eb9:13301:74)
    at __webpack_require__ (http://localhost:9876/base/test/test_index.js?e9733d491ba8dd8e6ccd1b6ec57c2b43b90d0eb9:20:30)
    at Object.<anonymous> (http://localhost:9876/base/test/test_index.js?e9733d491ba8dd8e6ccd1b6ec57c2b43b90d0eb9:34003:1)
HeadlessChrome 81.0.4044 (Windows 10.0.0) ERROR
  Uncaught TypeError: Cannot read property 'f' of undefined
  at webpack:///src/utils.js:308:42 <- test/test_index.js:179:185055

  TypeError: Cannot read property 'f' of undefined
      at Object.getParameterByName (webpack:///src/utils.js:308:42 <- test/test_index.js:179:185055)
      at Object.<anonymous> (webpack:///src/config.js:30:27 <- test/test_index.js:248:55165)
      at __webpack_require__ (webpack:///webpack/bootstrap%2067a68b5c76a10477dcfc:19:1 <- test/test_index.js:20:30)
      at Object.<anonymous> (test/test_index.js:166:69)
      at __webpack_require__ (webpack:///webpack/bootstrap%2067a68b5c76a10477dcfc:19:1 <- test/test_index.js:20:30)
      at Object.<anonymous> (test/test_index.js:873:68)
      at __webpack_require__ (webpack:///webpack/bootstrap%2067a68b5c76a10477dcfc:19:1 <- test/test_index.js:20:30)
      at Object.<anonymous> (webpack:///test/mocks/adloaderStub.js:2:1 <- test/test_index.js:13301:74)
      at __webpack_require__ (webpack:///webpack/bootstrap%2067a68b5c76a10477dcfc:19:1 <- test/test_index.js:20:30)
      at Object.<anonymous> (webpack:///test/test_index.js:2:1 <- test/test_index.js:34003:1)

Finished in 4.442 secs / 0 secs @ 15:35:53 GMT+0300 (GTB Daylight Time)

SUMMARY:
√ 0 tests completed
[15:35:53] 'testCoverage' errored after 1.45 min
[15:35:53] Error: Karma tests failed with exit code 1
    at C:\Users\fnedelcu\Desktop\prebid\Prebid.js\gulpfile.js:278:12
    at removeAllListeners (C:\Users\fnedelcu\Desktop\prebid\Prebid.js\node_modules\karma\lib\server.js:370:9)
    at webServer.close (C:\Users\fnedelcu\Desktop\prebid\Prebid.js\node_modules\karma\lib\server.js:381:13)
    at Server.close (net.js:1613:9)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:111:20)
    at Server.emit (events.js:208:7)
    at emitCloseNT (net.js:1664:8)
    at _combinedTickCallback (internal/process/next_tick.js:136:11)
    at process._tickDomainCallback (internal/process/next_tick.js:219:9)
[15:35:53] 'test-coverage' errored after 1.47 min

## Steps to reproduce
npm install
gulp test-coverage

## Platform details
- prebidjs - latest
- node: 8.17.0
- npm: 6.13.4
- os: Windows 10 Pro version 1909

**Comment by smenzer** [comment]
@florin-nedelcu thanks for calling this out. There's a temporary fix detailed here: https://github.com/prebid/Prebid.js/pull/5128 and I believe that https://github.com/prebid/Prebid.js/pull/5236 intends to clean it up (along with some other improvements)

**Comment by florin-nedelcu** [comment]
Thank you @smenzer! Seems like this temp fix does the job.

**Comment by bretg** [comment]
Going to close this one out - re-open as needed.
