### ISSUE TITLE
FAN adapter unit test errors IE11 WIN10

### ISSUE THREAD

**Issue by protonate** [prebid/Prebid.js#533]
The following unit test errors are occurring:

```
IE 11.0.0 (Windows 10 0.0.0) FAN Adapter requesting their API should send the placement IDs as an array FAILED
 218 -_-TypeError: Unable to get property 'params' of undefined or null reference
 8   -_-   at Anonymous function (/Users/ncozi/code/Prebid.js/test/spec/adapters/fan_spec.js:115:9)
IE 11.0.0 (Windows 10 0.0.0) FAN Adapter requesting their API sends the ad formats as FAN expects them FAILED
 218 -_-TypeError: Unable to get property 'params' of undefined or null reference
 8   -_-   at Anonymous function (/Users/ncozi/code/Prebid.js/test/spec/adapters/fan_spec.js:119:9)
IE 11.0.0 (Windows 10 0.0.0) helpers.url parse() extracts the pathname FAILED
 218 _-_Error: expected { protocol: 'http',
```

cc: @johngeorgewright @prebid/fan

**Comment by protonate** [comment]
This occurs in other browsers also:
* IE 11.0.0 (Windows 10 0.0.0)
* IE 11.0.0 (Windows 8.1 0.0.0)
* IE 11.0.0 (Windows 7 0.0.0)
* IE 9.0.0 (Windows 7 0.0.0)
*

**Comment by johngeorgewright** [comment]
The @protonate. Sorry for the late response, been on hols. I'll take a look as soon as I can.

**Comment by johngeorgewright** [comment]
I *think* I can see the issue.

*http://sinonjs.org/docs/#server*

> When faking XHR with IE you also need sinon-ie-1.17.5, which should be loaded after sinon-1.17.5.js.
