### ISSUE TITLE
npm install issue (jest/parse-domain?)

### ISSUE THREAD

**Issue by hnkhandev** [prebid/Prebid.js#5581]
## Type of issue
npm install issue

## Description
`Hussain@DESKTOP-MFR2DP6 MINGW64 ~/Desktop/prebid/Prebid.js-3.27.0
$ npm install

> fibers@4.0.3 install C:\Users\Hussain\Desktop\prebid\Prebid.js-3.27.0\node_modules\fibers
> node build.js || nodejs build.js

`win32-x64-72` exists; testing
Binary is fine; exiting

> core-js@2.6.11 postinstall C:\Users\Hussain\Desktop\prebid\Prebid.js-3.27.0\node_modules\babel-register\node_modules\core-js
> node -e "try{require('./postinstall')}catch(e){}"

Thank you for using core-js ( https://github.com/zloirock/core-js ) for polyfilling JavaScript standard library!

The project needs your help! Please consider supporting of core-js on Open Collective or Patreon:
> https://opencollective.com/core-js
> https://www.patreon.com/zloirock

Also, the author of core-js ( https://github.com/zloirock ) is looking for a good job -)

> core-js@2.6.11 postinstall C:\Users\Hussain\Desktop\prebid\Prebid.js-3.27.0\node_modules\babel-runtime\node_modules\core-js
> node -e "try{require('./postinstall')}catch(e){}"

> ejs@3.1.3 postinstall C:\Users\Hussain\Desktop\prebid\Prebid.js-3.27.0\node_modules\ejs
> node --harmony ./postinstall.js

Thank you for installing EJS: built with the Jake JavaScript build tool (https://jakejs.com/)

> ejs@2.7.4 postinstall C:\Users\Hussain\Desktop\prebid\Prebid.js-3.27.0\node_modules\webpack-bundle-analyzer\node_modules\ejs
> node ./postinstall.js

Thank you for installing EJS: built with the Jake JavaScript build tool (https://jakejs.com/)

> uglifyjs-webpack-plugin@0.4.6 postinstall C:\Users\Hussain\Desktop\prebid\Prebid.js-3.27.0\node_modules\uglifyjs-webpack-plugin
> node lib/post_install.js

> parse-domain@2.3.4 postinstall C:\Users\Hussain\Desktop\prebid\Prebid.js-3.27.0\node_modules\parse-domain
> run-s build:tries

> parse-domain@2.3.4 build:tries C:\Users\Hussain\Desktop\prebid\Prebid.js-3.27.0\node_modules\parse-domain
> node scripts/build-tries.js

Downloading public suffix list from https://publicsuffix.org/list/public_suffix_list.dat... (node:3844) [DEP0066] DeprecationWarning: OutgoingMessage.prototype._headers is deprecated
ok
Writing C:\Users\Hussain\Desktop\prebid\Prebid.js-3.27.0\node_modules\parse-domain\build\tries\icann.complete.json... ok
Writing C:\Users\Hussain\Desktop\prebid\Prebid.js-3.27.0\node_modules\parse-domain\build\tries\icann.light.json... ok
Writing C:\Users\Hussain\Desktop\prebid\Prebid.js-3.27.0\node_modules\parse-domain\build\tries\private.complete.json... ok
Running sanity check... C:\Users\Hussain\Desktop\prebid\Prebid.js-3.27.0\node_modules\.bin\jest:2
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")
          ^^^^^^^

SyntaxError: missing ) after argument list
    at wrapSafe (internal/modules/cjs/loader.js:1053:16)
    at Module._compile (internal/modules/cjs/loader.js:1101:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47

Could not update list of known top-level domains for parse-domain because of "Command failed: C:\Program Files\nodejs\node.exe C:\Users\Hussain\Desktop\prebid\Prebid.js-3.27.0\node_modules\.bin\jest
C:\Users\Hussain\Desktop\prebid\Prebid.js-3.27.0\node_modules\.bin\jest:2
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")
          ^^^^^^^

SyntaxError: missing ) after argument list
    at wrapSafe (internal/modules/cjs/loader.js:1053:16)
    at Module._compile (internal/modules/cjs/loader.js:1101:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47
"
Using possibly outdated prebuilt list from Sat Nov 02 2019

> core-js@3.6.5 postinstall C:\Users\Hussain\Desktop\prebid\Prebid.js-3.27.0\node_modules\core-js
> node -e "try{require('./postinstall')}catch(e){}"

> core-js-pure@3.6.5 postinstall C:\Users\Hussain\Desktop\prebid\Prebid.js-3.27.0\node_modules\core-js-pure
> node -e "try{require('./postinstall')}catch(e){}"

> sinon@4.5.0 postinstall C:\Users\Hussain\Desktop\prebid\Prebid.js-3.27.0\node_modules\sinon
> node scripts/support-sinon.js

Have some Γ¥ñ∩╕Å for Sinon? You can support the project via Open Collective:
 > https://opencollective.com/sinon/donate

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules\webpack-stream\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules\watchpack-chokidar2\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules\jest-haste-map\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules\glob-watcher\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules\documentation\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.3 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

added 2531 packages from 2497 contributors and audited 2546 packages in 32.629s

90 packages are looking for funding
  run `npm fund` for details

found 4771 vulnerabilities (4769 low, 2 high)
  run `npm audit fix` to fix them, or `npm audit` for details
`

## Steps to reproduce
running: npm install
node version: v12.18.3
npm version: 6.14.6

## Platform details
prebid 3.27.0

**Comment by hnkhandev** [comment]
formatting messed up
