### ISSUE TITLE
Unable to run a single spec file

### ISSUE THREAD

**Issue by monis0395** [prebid/Prebid.js#5647]
## Type of issue
- Bug

## Description
Currently in Prebid.js, running test cases require some pre-processing i.e. removing import/require statements, etc. 

Right now, this is only being done, when we are running all the spec files, but if someone tries to run a single spec file, we get an error saying that `Uncaught ReferenceError: require is not defined`. This happens because the *pre-processing* step is not happening while running a single spec file.

## Steps to reproduce
Consider an example to run only `api_spec.js`

```
gulp test-coverage --file=test/spec/api_spec.js
```

### Expected results
```
[18:52:35] Using gulpfile ~\Prebid.js\gulpfile.js
[18:52:35] Starting 'test-coverage'...
[18:52:35] Starting 'clean'...
[18:52:35] Finished 'clean' after 38 ms
[18:52:35] Starting 'testCoverage'...
i ｢wdm｣:
i ｢wdm｣: Compiled successfully.

START:
i ｢wdm｣: Compiling...
i ｢wdm｣: wait until bundle finished: noop
i ｢wdm｣:
i ｢wdm｣: Compiled successfully.
21 08 2020 18:52:47.597:INFO [karma-server]: Karma v4.4.1 server started at http://0.0.0.0:9876/
21 08 2020 18:52:47.600:INFO [launcher]: Launching browsers ChromeHeadless with concurrency 5
21 08 2020 18:52:47.607:INFO [launcher]: Starting browser ChromeHeadless
21 08 2020 18:52:48.235:INFO [HeadlessChrome 84.0.4147 (Windows 10.0.0)]: Connected on socket 60eNzQ5WgxI5cduHAAAA with id 62120196

Finished in 0.129 secs / 0.002 secs @ 18:52:48 GMT+0530 (India Standard Time)

SUMMARY:
√ 18 tests completed
[18:52:49] Finished 'testCoverage' after 13 s
[18:52:49] Finished 'test-coverage' after 13 s

```
### Actual results
```
[18:53:28] Using gulpfile ~\Prebid.js\gulpfile.js
[18:53:28] Starting 'test-coverage'...
[18:53:28] Starting 'clean'...
[18:53:28] Finished 'clean' after 70 ms
[18:53:28] Starting 'testCoverage'...
i ｢wdm｣:
i ｢wdm｣: Compiled successfully.

START:
21 08 2020 18:53:29.466:INFO [karma-server]: Karma v4.4.1 server started at http://0.0.0.0:9876/
21 08 2020 18:53:29.470:INFO [launcher]: Launching browsers ChromeHeadless with concurrency 5
21 08 2020 18:53:29.479:INFO [launcher]: Starting browser ChromeHeadless
21 08 2020 18:53:30.247:INFO [HeadlessChrome 84.0.4147 (Windows 10.0.0)]: Connected on socket vVwUjSw4MbvEXYUkAAAA with id 55414
HeadlessChrome 84.0.4147 (Windows 10.0.0) ERROR
  Uncaught ReferenceError: require is not defined
  at test/spec/api_spec.js:1:14

  ReferenceError: require is not defined
      at test/spec/api_spec.js:1:14

Finished in 0.403 secs / 0 secs @ 18:53:30 GMT+0530 (India Standard Time)

SUMMARY:
√ 0 tests completed
[18:53:30] 'testCoverage' errored after 2.41 s
[18:53:30] Error: Karma tests failed with exit code 1
    at C:\Users\Prebid.js\gulpfile.js:279:12
    at removeAllListeners (C:\Users\Prebid.js\node_modules\karma\lib\server.js:370:9)
    at webServer.close (C:\Users\Prebid.js\node_modules\karma\lib\server.js:381:13)
    at Server.close (net.js:1556:9)
    at Object.onceWrapper (events.js:277:13)
    at Server.emit (events.js:194:15)
    at Server.EventEmitter.emit (domain.js:459:23)
    at emitCloseNT (net.js:1609:8)
    at process._tickCallback (internal/process/next_tick.js:63:19)
[18:53:30] 'test-coverage' errored after 2.49 s

```

**Comment by jsnellbaker** [comment]
The linked PR has been reviewed and merged.
