### ISSUE TITLE
Changing globalVarName causes gulp serve tests to fail

### ISSUE THREAD

**Issue by SaboHimself** [prebid/Prebid.js#6060]
## Type of issue
- Bug

## Description
`richaudienceBidAdapter_spec.js` is currently causing gulp serve to fail when changing `globalVarName` in `package.json`

## Steps to reproduce
Change `globalVarName` in `package.json` 

Run 
```
gulp serve --modules=modules.json
```

### Expected results
```
[12:27:14] Using gulpfile ~/Prebid.js/gulpfile.js
[12:27:14] Starting 'serve'...
[12:27:14] Starting 'clean'...
[12:27:14] Finished 'clean' after 53 ms
[12:27:14] Starting 'lint'...
[12:27:39] Finished 'lint' after 25 s
[12:27:39] Starting 'build-bundle-dev'...
[12:27:39] Starting 'watch'...
[12:27:39] Starting 'test'...
[12:27:39] Starting 'makeDevpackPkg'...
[12:27:39] Starting server...
[12:27:39] Finished 'watch' after 24 ms
[12:27:39] Server started http://localhost:9999
[12:27:39] LiveReload started on port 35729
[12:27:39] Running server

START:
ℹ ｢wdm｣: 
ℹ ｢wdm｣: Compiled successfully.
ℹ ｢wdm｣: Compiling...
⚠ ｢wdm｣: 
ℹ ｢wdm｣: Compiled with warnings.
01 12 2020 12:28:22.692:INFO [karma-server]: Karma v4.4.1 server started at http://0.0.0.0:9876/
01 12 2020 12:28:22.693:INFO [launcher]: Launching browsers ChromeHeadless with concurrency 5
01 12 2020 12:28:22.698:INFO [launcher]: Starting browser ChromeHeadless
01 12 2020 12:28:23.370:INFO [HeadlessChrome 87.0.4280 (Mac OS X 11.0.0)]: Connected on socket xbRtBUf9Ek60jvjEAAAA with id 92720484

[12:28:41] Finished 'makeDevpackPkg' after 1.03 min
[12:28:41] Starting 'bound gulpBundle'...
[12:28:41] Concatenating files:
 [...]
[12:28:41] Appending pbjs.processQueue();
[12:28:41] Generating bundle: prebid.js
[12:28:42] Finished 'bound gulpBundle' after 695 ms
[12:28:42] Finished 'build-bundle-dev' after 1.05 min

Finished in 9.751 secs / 5.297 secs @ 12:28:43 GMT+0000 (Greenwich Mean Time)

SUMMARY:
✔ 7076 tests completed
ℹ 5 tests skipped
[12:28:43] Finished 'test' after 1.07 min
[12:28:43] Finished 'serve' after 1.48 min
```
### Actual results
```
[12:37:21] Using gulpfile ~/Prebid.js/gulpfile.js
[12:37:21] Starting 'serve'...
[12:37:21] Starting 'clean'...
[12:37:21] Finished 'clean' after 90 ms
[12:37:21] Starting 'lint'...
[12:37:45] Finished 'lint' after 24 s
[12:37:45] Starting 'build-bundle-dev'...
[12:37:45] Starting 'watch'...
[12:37:45] Starting 'test'...
[12:37:45] Starting 'makeDevpackPkg'...
[12:37:45] Starting server...
[12:37:45] Finished 'watch' after 20 ms
[12:37:45] Server started http://localhost:9999
[12:37:45] LiveReload started on port 35729
[12:37:45] Running server

START:
ℹ ｢wdm｣: 
ℹ ｢wdm｣: Compiled successfully.
ℹ ｢wdm｣: Compiling...
⚠ ｢wdm｣: 
ℹ ｢wdm｣: Compiled with warnings.
01 12 2020 12:38:27.973:INFO [karma-server]: Karma v4.4.1 server started at http://0.0.0.0:9876/
01 12 2020 12:38:27.974:INFO [launcher]: Launching browsers ChromeHeadless with concurrency 5
01 12 2020 12:38:28.149:INFO [launcher]: Starting browser ChromeHeadless
01 12 2020 12:38:28.586:INFO [HeadlessChrome 87.0.4280 (Mac OS X 11.0.0)]: Connected on socket xFzS_ZdlTBo6PgHKAAAA with id 2724439

HeadlessChrome 87.0.4280 (Mac OS X 11.0.0) ERROR
  Uncaught ReferenceError: pbjs is not defined
  at webpack:///test/spec/modules/richaudienceBidAdapter_spec.js:351:5 <- test/test_index.js:323043:5
  
  ReferenceError: pbjs is not defined
      at Suite.<anonymous> (webpack:///test/spec/modules/richaudienceBidAdapter_spec.js:351:5 <- test/test_index.js:323043:5)
      at Object.create (node_modules/mocha/mocha.js:720:19)
      at context.describe.context.context (node_modules/mocha/mocha.js:532:27)
      at Suite.<anonymous> (webpack:///test/spec/modules/richaudienceBidAdapter_spec.js:350:3 <- test/test_index.js:323042:3)
      at Object.create (node_modules/mocha/mocha.js:720:19)
      at context.describe.context.context (node_modules/mocha/mocha.js:532:27)
      at Object.<anonymous> (webpack:///test/spec/modules/richaudienceBidAdapter_spec.js:9:1 <- test/test_index.js:322735:1)
      at __webpack_require__ (webpack:///webpack/bootstrap%201d6489364d5227545e4b:19:1 <- test/test_index.js:20:30)
      at webpackContext (webpack:///test%20_spec$:382:1 <- test/test_index.js:53596:9)
      at Array.forEach (<anonymous>)

Finished in 11.732 secs / 0 secs @ 12:38:40 GMT+0000 (Greenwich Mean Time)

SUMMARY:
✔ 0 tests completed
[12:38:43] 'test' errored after 58 s
[12:38:43] Error: Karma tests failed with exit code 1
    at /Prebid.js/gulpfile.js:280:12
    at removeAllListeners (/Prebid.js/node_modules/karma/lib/server.js:370:9)
    at /Prebid.js/node_modules/karma/lib/server.js:381:13
    at Server.close (net.js:1519:9)
    at Object.onceWrapper (events.js:291:20)
    at Server.emit (events.js:208:15)
    at Server.EventEmitter.emit (domain.js:499:23)
    at emitCloseNT (net.js:1572:8)
    at processTicksAndRejections (internal/process/task_queues.js:77:11)
[12:38:43] 'serve' errored after 1.37 min
[12:38:43] The following tasks did not complete: build-bundle-dev, makeDevpackPkg
[12:38:43] Did you forget to signal async completion?
```

**Comment by pm-harshad-mane** [comment]
Thank you @SaboHimself for reporting the bug. I have raised a PR to fix it. #6069
