### ISSUE TITLE
Run e2e in local environment instead of cloud (ie. Browserstack)

### ISSUE THREAD

**Issue by giannisgpa** [prebid/Prebid.js#6552]
## Type of issue
Question
How to run e2e tests after on local environment rather than any cloud service (like Browserstack) ?

## Description
I have just cloned the repo, did all the appropriate installs, and tried to run e2e test for one specific spec. However i get an error saying the above:
```bash
Execution of 3 spec files started at 2021-04-08T15:20:39.172Z

[2-0] RUNNING in firefox - /test/spec/e2e/banner/basic_banner_ad.spec.js
[1-0] RUNNING in chrome - /test/spec/e2e/banner/basic_banner_ad.spec.js
[0-0] RUNNING in ie - /test/spec/e2e/banner/basic_banner_ad.spec.js
[0-0]  Error:  A "user" or "key" was provided but could not be connected to a known cloud service (Sauce Labs, Browerstack or Testingbot). Please check if given user and key properties are correct!
[1-0]  Error:  A "user" or "key" was provided but could not be connected to a known cloud service (Sauce Labs, Browerstack or Testingbot). Please check if given user and key properties are correct!
[2-0]  Error:  A "user" or "key" was provided but could not be connected to a known cloud service (Sauce Labs, Browerstack or Testingbot). Please check if given user and key properties are correct!
[0-0] FAILED in ie - /test/spec/e2e/banner/basic_banner_ad.spec.js
[1-0] FAILED in chrome - /test/spec/e2e/banner/basic_banner_ad.spec.js
[2-0] FAILED in firefox - /test/spec/e2e/banner/basic_banner_ad.spec.js

Spec Files:      0 passed, 3 failed, 3 total (100% completed) in 00:00:56 

[18:21:35] 'test' errored after 58 s
[18:21:35] Error: Tests failed with error: Error: Command failed: /home/giannisg/projects/Prebid.js/node_modules/.bin/wdio /home/giannisg/projects/Prebid.js/wdio.conf.js --spec test/spec/e2e/banner/basic_banner_ad.spec.js
    at /home/giannisg/projects/Prebid.js/gulpfile.js:283:14
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
[18:21:35] 'e2e-test' errored after 1.55 min
```

Is it possible to run e2e tests in the local environment and how to skip e2e testing on cloud providers? Is there any miss-configuration from my side?
thanks in advance

## Steps to reproduce
The command i execute to run e2e tests:
```bash
node_modules/.bin/gulp e2e-test --file "test/spec/e2e/banner/basic_banner_ad.spec.js" --host localhost
```
### Expected results
To have e2e testing running locally instead of any cloud provider

**Comment by ChrisHuie** [comment]
For the e2e tests I am not sure of a way to currently run them locally in containers as opposed to in the cloud with CircleCi. This has come up a few times though so not sure how big a lift it would be to create a dockerfile with the test configurations.

**Comment by ChrisHuie** [comment]
feature currently not available
