### ISSUE TITLE
fluctBidAdapter uses URLSearchParams that is not available in IE

### ISSUE THREAD

**Issue by pm-harshad-mane** [prebid/Prebid.js#7467]
## Type of issue
BUG

## Description
fluctBidAdapter uses URLSearchParams that is not available in IE.
https://github.com/prebid/Prebid.js/blob/master/modules/fluctBidAdapter.js#L51 
https://developer.mozilla.org/en-US/docs/Web/API/URLSearchParams#browser_compatibility
Found the following test failing on PrebidJS CI
```
sends bid request to ENDPOINT via POST
     fluctAdapter buildRequests
     ReferenceError: 'URLSearchParams' is undefined
   at Anonymous function (webpack:///modules/fluctBidAdapter.js:51:7 <- test/test_index.js:313318:7)
   at _each (webpack:///src/utils.js:399:29 <- test/test_index.js:604:29)
   at buildRequests (webpack:///modules/fluctBidAdapter.js:34:5 <- test/test_index.js:313302:5)
   at Anonymous function (webpack:///test/spec/modules/fluctBidAdapter_spec.js:78:7 <- test/test_index.js:313144:7)
```

**Comment by pm-harshad-mane** [comment]
The bidder code was updated on 16th Sept.

https://github.com/prebid/Prebid.js/commit/51c3c0d320d745e8661a2f0fe102af330fc3eb26#diff-c599b4560f40e527fc2fa1de536e8007383e7831eb6c4c1d035042984c1cfe59

**Comment by ChrisHuie** [comment]
pr #7478 polyfills this issue
